#!/bin/bash

#Initial wifi interface configuration
ifconfig wlan0 down

sleep 1

ifconfig wlan0 10.0.0.1 netmask 255.255.255.0
ifconfig wlan0 up

sleep 1

killall dnsmasq

sleep 1

###########Start dnsmasq, modify if required##########
if [ -z "$(ps -e | grep dnsmasq)" ]
then
 dnsmasq
fi
###########

sleep 1

#Enable NAT
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE
iptables --append FORWARD --in-interface wlan0 -j ACCEPT

sysctl -w net.ipv4.ip_forward=1

#start hostapd
hostapd -B /etc/hostapd/hostapd.conf
